### ISSUE TITLE
Frontend > Style > Remover todas as Notificações, antes de lançar uma nova.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-web#102]
# OVERVIEW 
- Para melhorar a experiência do usuário, evitando que várias notificações sejam floodadas na página, é necessário que, antes de uma notificação ser enviada, todas as outras sejam removidas antes.
- Para isso, basta utilizar a função `ElNotification.closeAll();` antes de chamar uma notificação;

# TASK
- [x] Utilizar a função `ElNotification.closeAll();` antes de chamar uma notificação na Página de Membros;
- [x] Utilizar a função `ElNotification.closeAll();` antes de chamar uma notificação na Página de Projetos;
- [x] Utilizar a função `ElNotification.closeAll();` antes de chamar uma notificação na Página de Links;
- [x] Utilizar a função `ElNotification.closeAll();` antes de chamar uma notificação na Página de Atualizações de Projetos;

**Comment by ManoMax** [comment]
https://github.com/codexjr-dev/dashboard-codex-web/pull/104
