### ISSUE TITLE
Frontend > Feature > Criar Página Perfil do Projeto.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-web#119]
# OVERVIEW 
- Agora com a feature aprovada e com uma prototipagem realizada, desenvolva a nova Página `Perfil do Projeto`;
- Para isso, será necessário / interessante:
  - Mudar o nome do arquivo "Project.vue" para "ProjectList.vue" e atualizar os redirecionamentos;
    - index.js (4 locais)
    - ViewNews (2 locais)
    - Project.vue (1 local)
  - Criar um novo arquivo "Project.vue";
  - Redirecionar o botão de "Visualizar Projeto" para a nova página Project.vue;
  - Desenvolver o Project.vue.

# TASK
- [x] Mudar o nome do arquivo "Project.vue" para "ProjectList.vue" e atualizar os redirecionamentos;
  - [x] index.js (4 locais)
  - [x] ViewNews (2 locais)
  - [x] Project.vue (1 local)
  - [x] Sidebar.vue (1 local)
  - [x] AllNews.js (1 local) 
- [x] Criar um novo arquivo "Project.vue";
- [x] Redirecionar o botão de "Visualizar Projeto" para a nova página Project.vue;
- [x] Desenvolver o Project.vue.

**Comment by FLuiz22** [comment]
https://github.com/codexjr-dev/projexa-web/pull/138
