### ISSUE TITLE
Frontend > Feature > Tornar as colunas dos cards (membros, projetos, links) com tamanhos adaptáveis.

### ISSUE THREAD

**Issue by FLuiz22** [codexjr-dev/projexa-web#143]
# OVERVIEW

- As colunas na página de membros, projetos e links tem seus tamanhos fixos, mas certas colunas como a de data não precisa de tanto espaço pois sempre vai ter o mesmo tamanho e mesmo assim possui mais espaço do que o necessário, enquanto o campo de nome pode precisar de mais espaço, logo vê-se a necessidade que essas colunas tenham tamanhos variados de acordo com o conteúdo nessa coluna;

# TASKS

- [ ] Tornar as colunas da página membros com tamanho adaptável;
- [ ] Tornar as colunas da página projetos com tamanho adaptável;
- [ ] Tornar as colunas da página links com tamanho adaptável;
