### ISSUE TITLE
Frontend > Fix > Bug ao visualizar os nomes dos integrantes do Time do Projeto.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-web#28]
# OVERVIEW 
- Ao editar ou visualizar um Projeto, por algum motivo, mesmo com as informações vindo corretamente do Backend, a exibição dos nomes dos integrantes está sendo exposta de modo incorreto (repetindo o nome de um deles).

# TASK
- [x] Solucionar e corrigir a exibição incorreta dos nomes dos integrantes do projeto, no model de visualização de projetos.
- [x] Solucionar e corrigir a exibição incorreta dos nomes dos integrantes do projeto, no model de edição de projetos.
- [x] Aproveitar a task e remover o console.log presente no botão de editar projeto.

**Comment by ManoMax** [comment]
https://github.com/codexjr-dev/dashboard-codex-web/pull/42
