### ISSUE TITLE
Frontend > Refactor > Remover a exclusividade do mozilla para partes do código

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-web#33]
# OVERVIEW 
- Por algum motivo, foi implementado uma funcionalidade no Frontend (algo como "moz") no qual certos componentes são reconhecidos apenas no Mozzila. 

# TASK
- [x] Remova ou atualize essas configurações para o sistema seja igualmente visto no Mozzila e no Chrome.
- [x] Analise a fonte configurada no sistema, sem o moz.
- [x] Analise a Home com e sem o moz.
- [x] Defina a melhor solução (fique livre).

**Comment by maahog** [comment]
https://github.com/codexjr-dev/dashboard-codex-web/pull/53
