### ISSUE TITLE
Frontend > Feature > [Atualizações de Projetos] Criar Model de Adicionar Atualização.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-web#44]
# OVERVIEW 
- Com os dois novos botões presentes em cada ocorrência da listagem de projetos.
- No primeiro, devemos redirecionar o usuário para o Model de `criar uma nova atualização`;

# TASK
- [x] Criar Model de `criar uma nova atualização`;
- [x] Redirecionar usuário para esse Model;
- [x] Enviar requisição para o Backend, com esse Model;

# Links:
- Issue of Backend: https://github.com/codexjr-dev/dashboard-codex-api/issues/40
- Link in Backend Project: https://github.com/orgs/codexjr-dev/projects/34/views/1?pane=issue&itemId=37557104

**Comment by FLuiz22** [comment]
#81
