### ISSUE TITLE
Frontend > Feature > [Atualizações de Projetos] Criar Model de Visualizar Atualizações.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-web#45]
# OVERVIEW 
- Com os dois novos botões presentes em cada ocorrência da listagem de projetos.
- No segundo, devemos redirecionar o usuário para o Model de `visualizar atualizações`;

# TASK
- [ ] Criar Model de `visualizar atualizações`;
- [ ] Redirecionar usuário para esse Model;
- [ ] Enviar requisição para o Backend, com esse Model;

# Links:
- Issue of Backend: https://github.com/codexjr-dev/dashboard-codex-api/issues/40
- Link in Backend Project: https://github.com/orgs/codexjr-dev/projects/34/views/1?pane=issue&itemId=37557104

**Comment by ManoMax** [comment]
https://github.com/codexjr-dev/dashboard-codex-web/pull/88
