### ISSUE TITLE
Frontend > Style > Adicionar ícones aos botões presentes nos cards da Página Member.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-web#52]
# OVERVIEW 
- Atualmente, o sistema conta com botões sem ícones, apenas com a visualização de cores;
- Diferentemente de como está na prototipação atual, onde os botões possuem legendas de sua funcionalidades `visualizar`, `editar` e `excluir`, será interessante utilizar ícones (talvez até com cores respectivas - ex: visualizar verde, editar azul e excluir vermelho) para melhoras a UI UX;

# TASK
- [x] Atualize o ícone de visualizar dos cards;
- [x] Atualize o ícone de editar dos cards;
- [x] Atualize o ícone de excluir dos cards;

**Comment by ManoMax** [comment]
https://github.com/codexjr-dev/dashboard-codex-web/pull/56
