### ISSUE TITLE
Frontend > Style > Configurar espaçamento (:width) dos el-table-column da Página de Projetos.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-web#72]
# OVERVIEW 
- A Página de Projetos possui 5 principais colunas em cada card: `Nome`, `Descrição`, `Time`, `Data de Início` e `Ações`.
- Cada um possui um espaçamento similar, no entanto, alguns precisam ter mais espaço do que outros.
- Sendo assim, configure o espaçamento (:width) das colunas para que `Descrição`, `Time` e `Ações` tenham um pouco mais de espaço do que `Nome` e `Data de Inicio` (que precisam de um espaçamento um pouco menor para ficar bem compreensível.

# TASK
- [x] Configure o espaçamento de `Nome` para que o mesmo fique adequadamente visível;
- [x] Configure o espaçamento de `Descrição` para que o mesmo fique adequadamente visível;
- [x] Configure o espaçamento de `Time` para que o mesmo fique adequadamente visível;
- [x] Configure o espaçamento de `Data de Inicio` para que o mesmo fique adequadamente visível;
- [x] Configure o espaçamento de `Ações` para que o mesmo fique adequadamente visível;

**Comment by nicolaskayamori** [comment]
#174
