### ISSUE TITLE
Frontend > Style > Configurar espaçamento (:width) dos el-table-column da Página de Membros.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-web#73]
# OVERVIEW 
- A Página de Membros possui 5 principais colunas em cada card: `Nome`, `Email`, `Função` (futuramente será chamada de "cargo"), `Data de Nascimento` e `Ações`.
- Cada um possui um espaçamento similar, no entanto, alguns precisam ter mais espaço do que outros.
- Sendo assim, configure o espaçamento (:width) das colunas para que `Nome` (que pode ser completo), `Email` e `Ações` tenham um pouco mais de espaço do que `Função` (que futuramente será chamada de "cargo") e `Data de Nascimento` (que precisam de um espaçamento um pouco menor para ficar bem compreensível.

# TASK
- [x] Configure o espaçamento de `Nome` para que o mesmo fique adequadamente visível;
- [x] Configure o espaçamento de `Email` para que o mesmo fique adequadamente visível;
- [x] Configure o espaçamento de `Função` para que o mesmo fique adequadamente visível;
- [x] Configure o espaçamento de `Data de Nascimento` para que o mesmo fique adequadamente visível;
- [x] Configure o espaçamento de `Ações` para que o mesmo fique adequadamente visível;

**Comment by carlos-lucenag** [comment]
#145

**Comment by FLuiz22** [comment]
# COMMENTS

- Ao revisar a issue, na minha tela, os botões da coluna ações somem como pode ser visto na seguinte imagem:



![Image](https://github.com/codexjr-dev/projexa-web/assets/64997111/b002ff1c-3969-48f2-961d-c70f70930c27)

**Comment by ManoMax** [comment]
# COMMENTS

- Por mais que adicione uma pequena informação a mais na tela, o `border` é um recurso muito útil e que, comparado ao seu benefício, acaba compensando existir o seu uso.
- Benefícios: A linha a mais não sobrecarrega o usuário visualmente e, ainda assim, adiciona uma feature super interessante para que o usuário adeque a tela para como achar melhor.

**Comment by nicolaskayamori** [comment]
#146
