### ISSUE TITLE
Frontend > Docs > Atualizar README.md

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-web#84]
# OVERVIEW 
- Na ideia de aprimorar a apresentação de nosso projeto, é interessante que uma boa documentação seja escrita.
- Desse modo, construa um padrão contendo uma `breve descrição`, `manual de instalação`, possíveis  `configurações`, `tecnologias utilizadas`, `versões` `colaboradores` e `licença`.
- Utilizando o mesmo padrão do novo README.md do Backend, reproduza o novo README.md do Frontend.

# TASK
- [x] Atualizar README.md com uma `breve descrição`; @maahog 
- [x] Atualizar README.md com um `manual de instalação`; @carlos-lucenag 
- [x] Atualizar README.md com as possíveis  `configurações`; @matheusvictoor 
- [x] Atualizar README.md com as `tecnologias utilizadas`; @Anaritamed 
- [x] Atualizar README.md com os `versões`; @FLuiz22 
- [x] Atualizar README.md com os `colaboradores`; @danieleolivs 
- [x] Atualizar README.md com uma `licença`.

# LINKS
- Link of Issue Backend: https://github.com/codexjr-dev/dashboard-codex-api/issues/59
- Link of Issue Backend in project: https://github.com/orgs/codexjr-dev/projects/34/views/1?pane=issue&itemId=38095299

**Comment by ManoMax** [comment]
# COMMENTS

- As configurações dos scripts para Linux ou Windows no `package.json` estão erradas;
- Ao menos, no meu Linux, o script está com o formato:
```JSON
"scripts": {
    "dev": "VUE_ENV=dev vite",
    "postinstall": "npm run build",
    "start": "VUE_ENV=prod node server.js",
    "build": "vite build",
    "preview": "vite preview --port 5050",
    "test:unit": "vitest --environment jsdom",
    "test:e2e": "start-server-and-test preview http://127.0.0.1:5050/ 'cypress open'",
    "test:e2e:ci": "start-server-and-test preview http://127.0.0.1:5050/ 'cypress run'",
    "lint": "eslint . --ext .vue,.js,.jsx,.cjs,.mjs --fix --ignore-path .gitignore"
  },
```

@matheusvictoor
