### ISSUE TITLE
Frontend > Docs > Criar o arquivo COLLAB.md

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/projexa-web#86]
# OVERVIEW 
- Na ideia de aprimorar a apresentação de nosso projeto, é interessante que uma boa documentação seja escrita.
- Desse modo, para orientar futuros devs que desejam colaborar no projeto, como eles podem se engajar, crie um arquivo chamado `COLLAB.md` na raiz do projeto;
- Esse arquivo deve mapear alguns tópicos como: 
  1. `Breve descrição da CodeX`;
  2. `Orientação de como entrar na CodeX`;
  3. `Breve descrição do projeto`;
  4. `Apresentação do Kanban do projeto`;
  5. `Como funciona cada coluna do Kanban`;
  6. `Como funcionam as TAGS do Kanban`;
  7. `Como criar uma Issue e passa-la pra Backlog`;
  8. `Como assinar uma Issue`;
  9. `Como realizar um PR`;
  10. `Apresentação das categorias de times (Devs, UI Designers, PO, SM, QA e TL) do Time Projexa`;
  11. `Exposição das Dailies, Sprint Review e Sprint Plannings`;
  12. `Exibir a prototipação do sistema`;
  13. `Contatos da CodeX Jr. (e-mail, site, Instagram e LinkedIn).`

# TASK
- [x] Criar um arquivo chamado `COLLAB.md` na raiz do projeto;
- [x] Criar uma `Breve descrição da CodeX`;
- [x] Criar uma `Orientação de como entrar na CodeX`;
- [x] Criar uma `Breve descrição do projeto`;
- [x] Criar uma `Apresentação do Kanban do projeto`;
- [x] Criar um tópico de `Como funciona cada coluna do Kanban`;
- [x] Criar um tópico de `Como funcionam as TAGS do Kanban`;
- [x] Criar um tópico de `Como criar uma Issue e passa-la pra Backlog`;
- [x] Criar um tópico de `Como assinar uma Issue`;
- [x] Criar um tópico de `Como realizar um PR`;
- [x] Criar uma `Apresentação das categorias de times (Devs, UI Designers, PO, SM, QA e TL) do Time Projexa`;
- [x] Criar uma `Exposição das Dailies, Sprint Review e Sprint Plannings`;
- [x] Criar uma `Exibição da prototipação do sistema`;
- [x] Criar um tópico de `Contatos da CodeX Jr. (e-mail, site, Instagram e LinkedIn).`

# LINKS
- Link of Issue README.md Backend: https://github.com/codexjr-dev/dashboard-codex-api/issues/59
- Link of Issue README.md Backend in project: https://github.com/orgs/codexjr-dev/projects/34/views/1?pane=issue&itemId=38095299 
- Link of Issue COLLAB.md Backend: https://github.com/codexjr-dev/dashboard-codex-api/issues/63
- Link of Issue COLLAB.md Backend in project: https://github.com/orgs/codexjr-dev/projects/34/views/1?pane=issue&itemId=38938271

**Comment by matheusvictoor** [comment]
#139
